version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    ports:
      - 9200:9200
    #volumes:
      #  - /root/elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    networks:
      - elk-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./cisco.yml:/usr/share/filebeat/modules.d/cisco.yml
      - ./logs:/var/log/cisco
        #command: "setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=[\'elasticsearch:9200\']"
        #command: "filebeat modules enable cisco && filebeat setup -e"
    networks:
      - elk-net
    depends_on:
      - elasticsearch
      - kibana

volumes:
  elasticsearch-data:

networks:
  elk-net:
