#filebeat.inputs:
#- type: log
#  enabled: true
#  paths:
#    - /var/log/cisco/*.log
#  fields:
#    log_type: cisco

filebeat.input:
- module: cisco

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "E8ggLyu5k7ITIlcesH2C"
  ssl.verification_mode: "none"

setup.kibana:
  host: "http://kibana:5601"

filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
