filebeat.input:
- module: cisco
  fields:
    - name: log_filename
      path: path
      processor: dissect
      tokenizer: "/var/log/cisco/%{filename}.log"
      target_prefix: 'dissect'


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "E8ggLyu5k7ITIlcesH2C"
  ssl.verification_mode: "none"

setup.kibana:
  host: "http://kibana:5601"

setup.template.settings:
 index.number_of_shards: 1

filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

processors:
  - dissect:
      tokenizer: "%{month} %{day} %{time}: %{event_type}: %{message}"
      field: "message"
      target_prefix: "dissect"
  - dissect:
      tokenizer: "/var/log/cisco/%{log_filename}.log"
      field: "log.file.path"
      target_prefix: ""
  - rename:
      fields:
        - { from: "log_filename", to: "host_ip" }
